<a href="https://colab.research.google.com/github/mathiascrepin/HTML_CSS/blob/master/Copie_de_analyse_donn%C3%A9es_covid_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importation des donnees 

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
  # importation des données 
confirmed_us=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv')
confirmed_global=pd.read_csv('https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
death_us = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv')
death_global= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
revorvered_global= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')

In [ ]:
# voir la taille des tableaux 

print(confirmed_us.shape)
print(confirmed_global.shape)
print(death_us.shape)
print(death_global.shape)
print(revorvered_global.shape)

(3340, 250)
(266, 243)
(3340, 251)
(266, 243)
(253, 243)

In [ ]:
confirmed_global.head(15)

                  Province/State       Country/Region  ...  9/15/20  9/16/20
0                            NaN          Afghanistan  ...    38815    38855
1                            NaN              Albania  ...    11672    11816
2                            NaN              Algeria  ...    48734    48966
3                            NaN              Andorra  ...     1438     1483
4                            NaN               Angola  ...     3569     3675
5                            NaN  Antigua and Barbuda  ...       95       95
6                            NaN            Argentina  ...   577338   589012
7                            NaN              Armenia  ...    46119    46376
8   Australian Capital Territory            Australia  ...      113      113
9                New South Wales            Australia  ...     4185     4190
10            Northern Territory            Australia  ...       33       33
11                    Queensland            Australia  ...     1149     1150
12               South Australia            Australia  ...      466      466
13                      Tasmania            Australia  ...      230      230
14                      Victoria            Australia  ...    19943    19970

[15 rows x 243 columns]

In [ ]:
death_global.head(15)

                  Province/State       Country/Region  ...  9/15/20  9/16/20
0                            NaN          Afghanistan  ...     1426     1436
1                            NaN              Albania  ...      340      343
2                            NaN              Algeria  ...     1632     1645
3                            NaN              Andorra  ...       53       53
4                            NaN               Angola  ...      139      143
5                            NaN  Antigua and Barbuda  ...        3        3
6                            NaN            Argentina  ...    11852    12116
7                            NaN              Armenia  ...      920      923
8   Australian Capital Territory            Australia  ...        3        3
9                New South Wales            Australia  ...       52       52
10            Northern Territory            Australia  ...        0        0
11                    Queensland            Australia  ...        6        6
12               South Australia            Australia  ...        4        4
13                      Tasmania            Australia  ...       13       13
14                      Victoria            Australia  ...      737      745

[15 rows x 243 columns]

In [ ]:
death_global.head(10)

                 Province/State       Country/Region  ...  9/15/20  9/16/20
0                           NaN          Afghanistan  ...     1426     1436
1                           NaN              Albania  ...      340      343
2                           NaN              Algeria  ...     1632     1645
3                           NaN              Andorra  ...       53       53
4                           NaN               Angola  ...      139      143
5                           NaN  Antigua and Barbuda  ...        3        3
6                           NaN            Argentina  ...    11852    12116
7                           NaN              Armenia  ...      920      923
8  Australian Capital Territory            Australia  ...        3        3
9               New South Wales            Australia  ...       52       52

[10 rows x 243 columns]

In [ ]:
death_global[death_global['Country/Region']=='China']

    Province/State Country/Region      Lat  ...  9/14/20  9/15/20  9/16/20
56           Anhui          China  31.8257  ...        6        6        6
57         Beijing          China  40.1824  ...        9        9        9
58       Chongqing          China  30.0572  ...        6        6        6
59          Fujian          China  26.0789  ...        1        1        1
60           Gansu          China  35.7518  ...        2        2        2
61       Guangdong          China  23.3417  ...        8        8        8
62         Guangxi          China  23.8298  ...        2        2        2
63         Guizhou          China  26.8154  ...        2        2        2
64          Hainan          China  19.1959  ...        6        6        6
65           Hebei          China  39.5490  ...        6        6        6
66    Heilongjiang          China  47.8620  ...       13       13       13
67           Henan          China  37.8957  ...       22       22       22
68       Hong Kong          China  22.3000  ...      101      102      102
69           Hubei          China  30.9756  ...     4512     4512     4512
70           Hunan          China  27.6104  ...        4        4        4
71  Inner Mongolia          China  44.0935  ...        1        1        1
72         Jiangsu          China  32.9711  ...        0        0        0
73         Jiangxi          China  27.6140  ...        1        1        1
74           Jilin          China  43.6661  ...        2        2        2
75        Liaoning          China  41.2956  ...        2        2        2
76           Macau          China  22.1667  ...        0        0        0
77         Ningxia          China  37.2692  ...        0        0        0
78         Qinghai          China  35.7452  ...        0        0        0
79         Shaanxi          China  35.1917  ...        3        3        3
80        Shandong          China  36.3427  ...        7        7        7
81        Shanghai          China  31.2020  ...        7        7        7
82          Shanxi          China  37.5777  ...        0        0        0
83         Sichuan          China  30.6171  ...        3        3        3
84         Tianjin          China  39.3054  ...        3        3        3
85           Tibet          China  31.6927  ...        0        0        0
86        Xinjiang          China  41.1129  ...        3        3        3
87          Yunnan          China  24.9740  ...        2        2        2
88        Zhejiang          China  29.1832  ...        1        1        1

[33 rows x 243 columns]

In [ ]:
# afficher uniquement les données du Benin 

death_global[death_global['Country/Region']=='Benin']

   Province/State Country/Region     Lat  ...  9/14/20  9/15/20  9/16/20
25            NaN          Benin  9.3077  ...       40       40       40

[1 rows x 243 columns]

In [ ]:
 # afficher toute  les colonnes

 death_global.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '9/7/20', '9/8/20', '9/9/20', '9/10/20', '9/11/20', '9/12/20',
       '9/13/20', '9/14/20', '9/15/20', '9/16/20'],
      dtype='object', length=243)

In [ ]:
# afficher les statistique niveau mondiale